name: Coverage

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: false
        default: ubuntu-latest
      php-version:
        type: string
        required: true
      dependency-versions:
        type: string
        required: false
        default: 'highest'

jobs:
  coverage:
    runs-on: ${{ inputs.os }}
    name: 'Coverage (${{ inputs.os }}, ${{ inputs.php-version }}, ${{ inputs.dependency-versions }})'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: mbstring, intl
          coverage: xdebug
      - name: Composer
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: ${{ inputs.dependencies }}
      - name: BlackBox
        run: php blackbox.php
        env:
          ENABLE_COVERAGE: 'true'
          BLACKBOX_SET_SIZE: 1
      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
